# Site settings
title: Martin Yang
email: martin0327@gmail.com
description: >
  A Philomath
author: Martin Yang
github_username:  martin0327

# GitHub Pages theme (official, zero setup)
theme: jekyll-theme-minimal

# Markdown & code highlighting
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  math_engine: katex
  syntax_highlighter: rouge

# Permalink style (clean URLs)
permalink: /:year/:month/:day/:title/

# Timezone (important for post dates)
timezone: Asia/Seoul

# Exclude junk files from build
exclude:
  - README.md
  - LICENSE
  - .gitignore

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed   # RSS feed
  - jekyll-seo-tag

# Optional but nice
show_downloads: false
